from django.urls import path
from .views import *

urlpatterns = [
    path('create_user/', registration, name="register"),
    path('dashboard/',dashboard, name="dashboard"),
    path('', loginuser, name="loginuser"),
    path('branch_manager/',branch_manager, name="branch_manager"),
    path('branch/', create_branch, name="branch"),
    path('agent/', agent, name="agent"),
    path('logout/', logoutuser, name="logoutuser"),
    path('create_customer/', create_customer, name='customer'),
    path('credit_premium/', credit_premium, name='credit_premium'),
    path('search/', search, name='search'),
    path('transfer_search/', transfer_search, name='transfer_search'),
    path('add_nominee/<int:customer_id>/', add_nominee, name='add_nominee'),
    path('see_nominee/<int:customer_id>/', see_nominee, name='see_nominee'),
    path('add_documents/<int:customer_id>/', add_documents, name='add_documents'),
    path('see_transation/<int:customer_id>/', see_transation, name='see_transation'),
    path('view_documents/<int:customer_id>/', view_documents, name='view_documents'),
    path('delete-document/<int:document_id>/', delete_document, name='delete_document'),
    path('transaction', transactions_report, name='transaction'),
    path('export_transactions_excel/<int:customer_id>/', export_transactions_excel, name='export_transactions_excel'),
    path('export_transactions_pdf/<int:customer_id>/', export_transactions_pdf, name='export_transactions_pdf'),
    path('export_transactions_excel/', all_export_transactions_excel, name='export_transactions_excel'),
    path('export_transactions_pdf/', export_transactions_pdf, name='export_transactions_pdf'),
    path('add_credit/<int:customer_id>/', credit_request, name='add_credit'),
    path('debit_amt/<int:customer_id>/', debit_request, name='debit_amt'),
    path('customer_debit_request/<int:customer_id>/', customer_debit_request, name='customer_debit_request'),
    path('search_customer/', search_customer, name='search_customer'),
    path('debit_search_customer/', debit_search_customer, name='debit_search_customer'),
    path('customer_debit_search/', customer_debit_search, name='customer_debit_search'),
    path('transfer_customer/', transfer_customer, name='transfer_customer'),
    path('transfer_records/', transfer_records, name='transfer_records'),
    path('transfer-amount/<int:sender_id>/<int:receiver_id>/', transfer_amount, name='transfer_amount'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('update_branch_manager/<int:user_id>/', update_branch_manager, name='update_branch_manager'),
    path('update_customer/<int:customer_id>/', update_customer, name='update_customer'),
    path('change_status/<int:customer_id>/', change_status, name='change_status'),
    path('approve_credit_request/<int:request_id>/', approve_transaction, name='approve_credit_request'),
    path('reject_credit_request/<int:request_id>/', reject_transaction, name='reject_credit_request'),
    path("delete_agent/<int:user_id>/", delete_agent, name="delete_agent"),
    path('delete-customer/<int:customer_id>/', delete_customer, name="delete_customer"),
]