# Generated by Django 5.1.5 on 2025-01-22 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=400)),
                ('branch_code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': 'MID'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch_manager.branch'),
        ),
        migrations.CreateModel(
            name='Branch_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
