# Generated by Django 5.1.5 on 2025-01-23 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0002_branch_customuser_branch_head_customuser_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150)),
                ('agents', models.ForeignKey(limit_choices_to={'user': 'LOW'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agents', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('branch_head', models.ForeignKey(blank=True, limit_choices_to={'user': 'MID'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Branch Head')),
            ],
            options={
                'verbose_name': 'Agent Assignment',
                'verbose_name_plural': 'Agent Assignments',
            },
        ),
    ]
