# Generated by Django 5.1.5 on 2025-01-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0005_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='scheme',
            field=models.CharField(choices=[('A', 'Monthy'), ('B', 'Half Yearly'), ('C', 'Yearly')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
