# Generated by Django 5.1.5 on 2025-01-31 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0006_remove_customer_bank_name_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='documents/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='branch_manager.customer')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='branch_manager.customer')),
            ],
            options={
                'verbose_name': 'Nominee',
                'verbose_name_plural': 'Nominees',
            },
        ),
    ]
