# Generated by Django 5.1.5 on 2025-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0008_creditrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='scheme',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('HALF YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=150),
        ),
    ]
