# Generated by Django 5.1.5 on 2025-02-24 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0009_alter_customer_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='creditrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterField(
            model_name='agentassignment',
            name='agents',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': 'LOW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agents', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user': 'LOW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_requests', to='branch_manager.customer'),
        ),
    ]
