# Generated by Django 5.1.5 on 2025-02-24 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0010_alter_agentassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'user': 'LOW'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_requests', to=settings.AUTH_USER_MODEL)),
                ('branch_head', models.ForeignKey(blank=True, limit_choices_to={'user': 'MID'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_requests', to='branch_manager.customer')),
            ],
        ),
    ]
