# Generated by Django 5.1.5 on 2025-03-01 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0011_transactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 0, 54, 59, 894010), null=True),
        ),
    ]
