# Generated by Django 5.1.5 on 2025-04-07 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0012_creditrequest_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 22, 33, 5, 329185), null=True),
        ),
    ]
