# Generated by Django 5.1.5 on 2025-04-07 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0013_customer_premium_alter_creditrequest_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 23, 44, 44, 900411), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='premium',
            field=models.IntegerField(default=0),
        ),
    ]
