# Generated by Django 5.1.5 on 2025-04-08 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0014_alter_creditrequest_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive')], default='DEACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 0, 13, 22, 79934), null=True),
        ),
    ]
