# Generated by Django 5.1.5 on 2025-05-03 18:36

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0015_customer_status_alter_creditrequest_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 4, 0, 6, 26, 901642), null=True),
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch_manager', models.ForeignKey(blank=True, limit_choices_to={'user': 'MID'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_handled', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='branch_manager.customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='branch_manager.customer')),
            ],
        ),
    ]
