# Generated by Django 4.1.5 on 2025-05-29 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0016_alter_creditrequest_created_time_transferrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 13, 3, 32, 474639), null=True),
        ),
    ]
