# Generated by Django 4.1.5 on 2025-05-31 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0017_alter_creditrequest_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 0, 22, 53, 494809), null=True),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 1, 0, 22, 53, 494809), null=True),
        ),
    ]
