# Generated by Django 4.1.5 on 2025-06-01 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0018_alter_creditrequest_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 0, 53, 25, 425862), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='scheme',
            field=models.CharField(choices=[('DDS 12 month', 'DDS 12 month'), ('DDS 6 month', 'DDS 6 month'), ('RD 12 month', 'RD 12 month'), ('RD 24 month', 'RD 24 month'), ('FD 1 year', 'FD 1 year'), ('FD 2 year', 'FD 2 year'), ('FD 3 year', 'FD 3 year'), ('FD 4 year', 'FD 4 year'), ('FD 5 year', 'FD 5 year'), ('MIS 1 year', 'MIS 1 year'), ('MIS 2 year', 'MIS 2 year'), ('MIS 3 year', 'MIS 3 year'), ('MIS 4 year', 'MIS 4 year'), ('MIS 5 year', 'MIS 5 year')], max_length=150),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 2, 0, 53, 25, 430688), null=True),
        ),
    ]
