# Generated by Django 4.1.5 on 2025-06-21 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0020_alter_creditrequest_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 21, 16, 34, 36, 156451), null=True),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='relation',
            field=models.CharField(choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SISTER', 'SISTER'), ('BROTHER', 'BROTHER'), ('SON', 'SON'), ('SPOUSE', 'SPOUSE'), ('FRIEND', 'FRIEND'), ('OTHER', 'OTHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 21, 16, 34, 36, 158001), null=True),
        ),
    ]
