# Generated by Django 4.1.5 on 2025-06-27 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0021_alter_creditrequest_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 18, 20, 5, 138795), null=True),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 27, 18, 20, 5, 138795), null=True),
        ),
    ]
