# Generated by Django 4.1.5 on 2025-06-27 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_manager', '0022_transactionrequest_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 18, 56, 22, 516416), null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 27, 18, 56, 22, 516416), null=True),
        ),
    ]
